### ISSUE TITLE
submit button on Phone Verify does not work on Chrome

### ISSUE THREAD

**Issue by munje** [bvantagelimited/ipification-showcase#8]
https://user-images.githubusercontent.com/4479405/103276160-19cab780-49c6-11eb-9a98-191e959e068e.mp4

**Comment by munje** [comment]
Chrome is on mobile device - Samsung A20e

**Comment by munje** [comment]
![Uploading WhatsApp Image 2020-12-29 at 11.11.13.jpeg…]()

**Comment by munje** [comment]
![WhatsApp Image 2020-12-29 at 11 11 13](https://user-images.githubusercontent.com/4479405/103276419-bf7e2680-49c6-11eb-93c5-1b6ac52371da.jpeg)

**Comment by lemanh2006** [comment]
Hi Milan, please click to Phone Verification button, I will add enter event on input

**Comment by lemanh2006** [comment]
![z2255485339094_5159f700d4da56d99879992a5a669eb8](https://user-images.githubusercontent.com/5046148/103391086-30018080-4b4a-11eb-8d6e-a15f360a7be8.jpg)

**Comment by lemanh2006** [comment]
I fix this issue, add event enter on phone input

**Comment by munje** [comment]
ok .. it is working now
